version: '3.8'
services:
  api:
    build: .
    container_name: twitter-clone-romanets-mongodb-client-frontend
    ports:
      - '2023:3000'
    volumes:
      - /app
      - /app/node_modules
    stdin_open: true
    tty: true 